USE MASTER;
go
-- Tạo Database QuanLyTuýeninh
IF DB_ID('QuanLyCafe') IS NOT NULL
	DROP DATABASE QuanLyCafe;
GO

CREATE DATABASE QuanLyCafe;
GO
-- Tạo Table.
USE QuanLyCafe;
GO
----TẠO TABLE TÀI KHOẢN.
IF OBJECT_ID('TAIKHOAN') IS NOT NULL
	DROP TABLE TAIKHOAN;
GO

CREATE TABLE TAIKHOAN
(
	IDNhanVien VARCHAR (5) NOT NULL,
	TaiKhoan VARCHAR (30) NOT NULL UNIQUE,
	MatKhau VARCHAR (30) NOT NULL,
	LoaiTaiKhoan int not null,
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY (IDNhanVien)
)
GO

IF OBJECT_ID('FUNC_CREATE_ID_NHANVIEN') IS NOT NULL 
	DROP FUNCTION FUNC_CREATE_ID_NHANVIEN;
GO

CREATE FUNCTION FUNC_CREATE_ID_NHANVIEN()
RETURNS VARCHAR (5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT (IDNhanVien) from NHANVIEN) = 0
			SET @ID = '0'
	ELSE 
		SELECT @ID = MAX(RIGHT(IDNhanVien, 3)) FROM NHANVIEN
		SELECT @ID = CASE
					WHEN @ID >= 0 AND @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT , @ID) + 1)
					WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT , @ID) + 1)
		END
	RETURN @ID
END
GO

IF OBJECT_ID('NHANVIEN') IS NOT NULL
	DROP TABLE NHANVIEN;
GO

CREATE TABLE NHANVIEN
(
	IDNhanVien VARCHAR (5) NOT NULL DEFAULT DBO.FUNC_CREATE_ID_NHANVIEN(),
	Ho NVARCHAR (10) NOT NULL,
	Ten NVARCHAR (20) NOT NULL,
	NgaySinh DATE NOT NULL,
	SDT VARCHAR(11) NULL,
	DiaChi NVARCHAR(100) NULL,
	Email VARCHAR(30) NULL,
	HinhNV VARCHAR(100) NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (IDNhanVien)
)
GO

IF OBJECT_ID('DANHMUC') IS NOT NULL 
	DROP TABLE DANHMUC;
GO

CREATE TABLE DANHMUC 
(
	IDDanhMuc INT IDENTITY (1,1) NOT NULL,
	TenDanhMuc NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_DANHMUC PRIMARY KEY (IDDanhMuc)
)
go



IF OBJECT_ID('FUNC_CREATE_ID_NUOCUONG') IS NOT NULL 
	DROP FUNCTION FUNC_CREATE_ID_NUOCUONG;
GO

CREATE FUNCTION FUNC_CREATE_ID_NUOCUONG()
RETURNS VARCHAR (5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT (IDMonNuoc) from NUOCUONG) = 0
			SET @ID = '0'
	ELSE 
		SELECT @ID = MAX(RIGHT(IDMonNuoc, 3)) FROM NUOCUONG
		SELECT @ID = CASE
					WHEN @ID >= 0 AND @ID < 9 THEN 'NU00' + CONVERT(CHAR, CONVERT(INT , @ID) + 1)
					WHEN @ID >= 9 THEN 'NU0' + CONVERT(CHAR, CONVERT(INT , @ID) + 1)
		END
	RETURN @ID
END
GO

IF OBJECT_ID('NUOCUONG') IS NOT NULL 
	DROP TABLE NUOCUONG;
GO

CREATE TABLE NUOCUONG
(
	IDMonNuoc VARCHAR(5) NOT NULL DEFAULT DBO.FUNC_CREATE_ID_NUOCUONG(),
	IDDanhMuc INT NOT NULL,
	TenMon NVARCHAR(30) NOT NULL UNIQUE,
	GiaTien INT NOT NULL,
	HinhNU VARCHAR(100) NULL,
	CONSTRAINT PK_NUOCUONG PRIMARY KEY (IDMonNuoc)
)
GO

IF OBJECT_ID('BAN') IS NOT NULL
	DROP TABLE BAN
GO

CREATE TABLE BAN
(
	IDBan INT IDENTITY (1 , 1) NOT NULL,
	TenBan NVARCHAR (20) NOT NULL UNIQUE,
	TrangThai BIT NOT NULL,
	IDHoaDon varchar(10) NULL,
	CONSTRAINT PK_BAN PRIMARY KEY (IDBan)
)
GO

IF OBJECT_ID('getNewID') IS NOT NULL
	DROP VIEW getNewID
GO

CREATE VIEW getNewID AS SELECT NEWID() AS new_id
GO

IF OBJECT_ID('FUNC_CREATE_ID_HOADON') IS NOT NULL
	DROP FUNCTION FUNC_CREATE_ID_HOADON
GO

CREATE FUNCTION FUNC_CREATE_ID_HOADON()
RETURNS VARCHAR(10)
AS 
BEGIN 
	DECLARE @ID VARCHAR(10) = ''
	WHILE (@ID = '' OR (SELECT IDHoaDon FROM HOADON WHERE IDHoaDon = @ID) IS NOT NULL)
	BEGIN
		SET @ID = CONVERT(nvarchar(10),LEFT(REPLACE((select new_id from getNewID),'-',''),10))
	END
	RETURN @ID
END
GO

IF OBJECT_ID('HOADON') IS NOT NULL
	DROP TABLE HOADON
GO

CREATE TABLE HOADON
(
	IDHoaDon VARCHAR(10) NOT NULL DEFAULT DBO.FUNC_CREATE_ID_HOADON(),
	IDNhanVien VARCHAR(5) NOT NULL,
	NgayLap DATETIME NOT NULL,
	TongTien INT NOT NULL,
	KhuyenMai VARCHAR(10) NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY (IDHoaDon)
)
GO

IF OBJECT_ID('CHITIETHOADON') IS NOT NULL
	DROP TABLE CHITIETHOADON
GO


CREATE TABLE CHITIETHOADON
(
	IDHoaDon VARCHAR(10) NOT NULL,
	IDMonNuoc VARCHAR(5) NOT NULL,
	SoLuong INT NOT NULL,
	GiaTien INT
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (IDHoaDon,IDMonNuoc)
)
GO

ALTER TABLE TAIKHOAN
WITH NOCHECK ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN
FOREIGN KEY (IDNhanVien) REFERENCES NHANVIEN (IDNhanVien)
GO

ALTER TABLE NUOCUONG
WITH NOCHECK ADD CONSTRAINT FK_NUOCUONG_DANHMUC
FOREIGN KEY (IDDanhMuc) REFERENCES DANHMUC (IDDanhMuc)
GO

ALTER TABLE HOADON
WITH NOCHECK ADD CONSTRAINT FK_HOADON_NHANVIEN
FOREIGN KEY (IDNhanVien) REFERENCES NHANVIEN (IDNhanVien)
GO

ALTER TABLE CHITIETHOADON
WITH NOCHECK ADD CONSTRAINT FK_CHITIETHOADON_HOADON
FOREIGN KEY (IDHoaDon) REFERENCES HOADON (IDHoaDon)
GO

ALTER TABLE BAN
WITH NOCHECK ADD CONSTRAINT FK_BAN_HOADON
FOREIGN KEY (IDHoaDon) REFERENCES HOADON (IDHoaDon)
GO

ALTER TABLE CHITIETHOADON
WITH NOCHECK ADD CONSTRAINT FK_CHITIETHOADON_NUOCUONG
FOREIGN KEY (IDMonNuoc) REFERENCES NUOCUONG (IDMonNuoc)
GO

