<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyCafe" Class="QuanLyCafeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-P8SSJG9\SQLEXPRESS;Initial Catalog=QuanLyCafe;Integrated Security=True" SettingsObjectName="ProjectMonHoc.Properties.Settings" SettingsPropertyName="QuanLyCafeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAN" Member="BANs">
    <Type Name="BAN">
      <Column Name="IDBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IDHoaDon" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="HOADON_BAN" Member="HOADON" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="IDHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IDMonNuoc" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="HOADON" IsForeignKey="true" />
      <Association Name="NUOCUONG_CHITIETHOADON" Member="NUOCUONG" ThisKey="IDMonNuoc" OtherKey="IDMonNuoc" Type="NUOCUONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUC" Member="DANHMUCs">
    <Type Name="DANHMUC">
      <Column Name="IDDanhMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="DANHMUC_NUOCUONG" Member="NUOCUONGs" ThisKey="IDDanhMuc" OtherKey="IDDanhMuc" Type="NUOCUONG" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="IDHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDNhanVien" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KhuyenMai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="HOADON_BAN" Member="BANs" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="BAN" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="CHITIETHOADON" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="IDNhanVien" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HinhNV" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="HOADON" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="TAIKHOAN" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="TAIKHOAN" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.NUOCUONG" Member="NUOCUONGs">
    <Type Name="NUOCUONG">
      <Column Name="IDMonNuoc" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDDanhMuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HinhNU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="NUOCUONG_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="IDMonNuoc" OtherKey="IDMonNuoc" Type="CHITIETHOADON" />
      <Association Name="DANHMUC_NUOCUONG" Member="DANHMUC" ThisKey="IDDanhMuc" OtherKey="IDDanhMuc" Type="DANHMUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="IDNhanVien" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaiKhoan" Member="TaiKhoan1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="NHANVIEN" ThisKey="IDNhanVien" OtherKey="IDNhanVien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>